[font]
size = 13

[font.normal]
family = "Blex Mono Nerd Font"

[window]
decorations = "none"
opacity = 0.96

[window.padding]
x = 7
y = 3

# GitHub Dark High Contrast (BG Modified to Pure Black)
[colors.primary]
background = '#000000'
foreground = '#f0f3f6'

[colors.cursor]
text = '#0a0c10'
cursor = '#f0f3f6'

[colors.normal]
black = '#7a828e'
red = '#ff9492'
green = '#26cd4d'
yellow = '#f0b72f'
blue = '#71b7ff'
magenta = '#cb9eff'
cyan = '#39c5cf'
white = '#d9dee3'

[colors.bright]
black = '#9ea7b3'
red = '#ffb1af'
green = '#4ae168'
yellow = '#f7c843'
blue = '#91cbff'
magenta = '#cb9eff'
cyan = '#39c5cf'
white = '#d9dee3'

[terminal]
[terminal.shell]
program = "tmux"
