#!/bin/bash

# A bash script that creates the necessary symlinks for setting up various of my
# configuration files (dotfiles)

ln -sf "$DOTFILES"/alacritty/alacritty.toml ~/.config/
ln -sf "$DOTFILES"/nvim/ ~/.config/
ln -sf "$DOTFILES"/zsh/.zshrc ~/
ln -sf "$DOTFILES"/tmux/.tmux.conf ~/
