#!/bin/bash

# A bash script that creates the necessary symlinks for setting up various of my
# configuration files (dotfiles)

DIR="/home/orphic/Repos/dotfiles"
CONFIG_DIR="/home/orphic/.config/"

ln -sf "$DIR"/alacritty/alacritty.toml "$CONFIG_DIR"
